In [64]:
import numpy as np
import math
def get_rms(records):
    """
    向量长度
    """
    return math.sqrt(sum([x ** 2 for x in records]))



In [90]:
import os  
path1=os.path.abspath('.')
path_file= path1+"\S-ben-ch2-N-CH2^2-c60"
# -*- coding:utf-8 -*-  
print( path_file )

C:\Users\华为\Desktop\phd\vesta\S-ben-ch2-N-CH2^2-c60


In [65]:
#input 2 atoms coordinate
A = np.array([-2.37125 ,-1.99855 ,1.08725])
B = np.array([-1.30774,-1.21381 ,0.36564])

In [66]:
get_rms(A)

3.2862046843585384

In [67]:
Zvector = A-B
Zvector

array([-1.06351, -0.78474,  0.72161])

In [68]:
# rotation matrix
Xvector = np.array([Zvector[0],Zvector[1],-(Zvector[0]**2+Zvector[1]**2)/Zvector[2]])
Yvector = np.array([Zvector[1],-Zvector[0],0])
P = np.array([Xvector/get_rms(Xvector),Yvector/get_rms(Yvector),Zvector/get_rms(Zvector)]).T

In [69]:
P

array([[-0.38559499, -0.59373883, -0.70625117],
       [-0.28452183,  0.80465782, -0.52112678],
       [-0.87770373,  0.        ,  0.47920368]])

In [70]:
invP=np.linalg.inv(P)
invP

array([[-3.85594988e-01, -2.84521830e-01, -8.77703728e-01],
       [-5.93738825e-01,  8.04657820e-01, -7.63582376e-17],
       [-7.06251168e-01, -5.21126780e-01,  4.79203680e-01]])

In [72]:
original = np.array([ 0.20543,-1.57082, 1.81219]).reshape(3,1)
print(original)
new=np.dot(invP,original)
new

[[ 0.20543]
 [-1.57082]
 [ 1.81219]]


array([[-1.22284612],
       [-1.38594436],
       [ 1.54191931]])

In [50]:
1.958286 *(-1.06351)  -1.385944* (-0.78474)+  (-0.194896)*(-1.06351)

-0.7877772043399998

In [92]:
with open("\python_molecule_zdrection.xyz",w+) as f1:
    with open("molecule.xyz") as f:
        for k,v in enumerate(f):
            if k == 0 or k == 1:
                line = v.strip()
            else:
                lst = v.strip().split()
                original = np.array([float(lst[1]),float(lst[2]),float(lst[3]) ]).reshape(3,1)
                new=np.dot(invP,original)
                for i in range(1,4):
                    lst[i] = new[i]
                line = '   '.join(lst)
                f1.writeline(line)
        f.close()
    f1.close()
    
with open("python_molecule_zdrection.xyz") as f:
    print(f.read())

SyntaxError: invalid syntax (<ipython-input-92-06a95f66cc07>, line 1)

In [5]:
dp=[[0]*7 for i in range(3)]
dp

[[0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0]]

In [6]:
dp[0][1]=1
dp

[[0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0]]