In [3]:
S_HCN_up=[       -6.588897  ,  0.973355 ,  -1.052981]
S_HCN_down=[       7.105454   , 1.145740 ,  -0.153929]

S_target_up=[  10.6232772178  ,  5.6992577984 ,   42.298758022   ]
S_target_down=[   10.4291060779 ,   5.6246057727  ,  28.9960799425  ]


In [4]:
import math
import numpy as np
T_location = np.array(S_target_up)-np.array(S_target_down)

T_location_norm = T_location.copy()
T_location_norm= T_location_norm/np.linalg.norm(T_location_norm)
originVector = np.array(S_HCN_up)-np.array(S_HCN_down)
originVector_norm = originVector/np.linalg.norm(originVector)
print(originVector)
print(T_location)
sita = math.acos(T_location_norm@originVector_norm)
n_vector = np.cross(T_location_norm,originVector_norm) 

n_vector=n_vector/np.linalg.norm(n_vector)

n_vector_invert = np.array((
[0,-n_vector[2],n_vector[1]],
[n_vector[2],0,-n_vector[0]],
[-n_vector[1],n_vector[0],0]
))

print(sita)
print(n_vector_invert)


I = np.array((
[1 ,  0 , 0],
[0 ,  1 , 0],
[0 ,  0 , 1]
))

R_w2c = I + math.sin(sita)*n_vector_invert + n_vector_invert@(n_vector_invert)*(1-math.cos(sita))

[-13.694351  -0.172385  -0.899052]
[ 0.19417114  0.07465203 13.30267808]
1.6510120134742525
[[ 0.         -0.00543278 -0.99991045]
 [ 0.00543278  0.         -0.01223024]
 [ 0.99991045  0.01223024  0.        ]]


In [5]:
np.dot(originVector,R_w2c)

array([ 0.20030977,  0.07701211, 13.72323597])

In [ ]:
S1= [ 7.712919650215356 , 10.240018110800758, -15.024762326175564]
Sshould=[11.4807219596 ,   5.1879040988 ,   28.4894975676   ]


In [6]:
with open("python_HCNmiddlech2040.xyz",'w') as f1:
    with open("HCNmiddlech2040.xyz") as f:
        for k,v in enumerate(f):
            if k == 0 or k == 1:
                line = v
            else:
                lst = v.strip().split()
                original = np.array([float(lst[1]),float(lst[2]),float(lst[3]) ])
                new=np.dot(original,R_w2c)
                for i in range(1,4):
                    lst[i] = str(new[i-1])
                line = '   '.join(lst)+"\n"
            f1.writelines(line)
        f.close()
    f1.close()
    
with open("python_HCNmiddlech2040.xyz") as f:
    print(f.read())



39

C   1.032091608262799   4.054543190541927   0.6877093343161772
N   1.2481420458105994   3.656760888108279   1.764975113250972
H   0.8329792693451102   4.424691318362451   -0.3066503438042144
C   0.026594071990582682   0.28975956103882694   5.130893628099743
C   0.5842345172926878   0.9873545667531557   4.044255769648412
C   1.0458846437713474   0.2863786036982156   2.9209427543608486
C   0.9656639733392337   -1.115418129745362   2.8409613790579846
C   -0.08404820087352499   -1.1128627317444257   5.0578728899980545
C   0.3803055011976499   -1.7944188959083676   3.929186850697076
C   -0.7197294321792017   -1.0179602917211095   -2.919510685628001
H   1.4962476395511342   0.8577973699553136   2.101285107645178
S   -0.5302610100573025   1.0892224733836615   6.633413169981499
H   -0.5169528502231903   -1.6736036481177834   5.8932416069441755
H   0.3049664071957123   -2.8883182388694073   3.9018002984246216
H   0.6795881299651494   2.0780296813546735   4.061697267327104
C   -1.72497478293

In [7]:
S_before=[ -0.7305707789454892 ,  1.0122103591080631 ,  -7.089822801496686]
S_after=[  10.4291060779 ,   5.6246057727 ,   28.9960799425 ]
Sdiff=[S_after[i] - S_before[i] for i in range(3)]

In [9]:
def str_float_z(num):
    return str(float(num)+ Sdiff[2])
def str_float_x(num):
    return str(float(num)+Sdiff[0])
def str_float_y(num):
    return str(float(num)+Sdiff[1])

with open("ch2040_HCNmiddle_negf.xyz",'w') as f1:
    with open("bifonazole_right_negf.xyz") as f:
        for k,v in enumerate(f):
            if k<=301:
                line = v
                f1.writelines(line)
        f.close()
    with open("python_HCNmiddlech2040.xyz") as f:
        for k,v in enumerate(f):
            if k == 0 or k == 1:
                continue
            else:
                lst = v.strip().split()
                lst[3]=str_float_z(lst[3])
                lst[2]=str_float_y(lst[2])
                lst[1]=str_float_x(lst[1])
                lst.append('S') 
                line = '    '.join(lst) +'\n'
                f1.writelines(line)
        f.close()
    with open("bifonazole_right_negf.xyz") as f:
        for k,v in enumerate(f):
            if k<=335:
                continue
            else:
                line = v
                f1.writelines(line)
        f.close()
    f1.close()
    
with open("ch2040_HCNmiddle_negf.xyz") as f:
    print(f.read())

 420
 i =       82, E =     -3365.3998523447
Au     0.000000     0.000000     0.000000     L3
Au     8.760000     0.000000     0.000000     L3
Au     4.380000     7.586382     0.000000     L3
Au     13.140000     7.586382     0.000000     L3
Au     2.920000     0.000000     0.000000     L3
Au     11.680000     0.000000     0.000000     L3
Au     7.300000     7.586382     0.000000     L3
Au     16.059999     7.586382     0.000000     L3
Au     5.840000     0.000000     0.000000     L3
Au     10.220000     7.586382     0.000000     L3
Au     1.460000     2.528794     0.000000     L3
Au     10.220000     2.528794     0.000000     L3
Au     5.840000     10.115176     0.000000     L3
Au     14.600000     10.115176     0.000000     L3
Au     4.380000     2.528794     0.000000     L3
Au     13.140000     2.528794     0.000000     L3
Au     8.760000     10.115176     0.000000     L3
Au     17.520000     10.115176     0.000000     L3
Au     7.300000     2.528794     0.000000     L3
Au     11.68